//
//  DetailInterfaces.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
}

protocol DetailViewInterface: ViewInterface {
}

protocol DetailPresenterInterface: PresenterInterface {
    func getImageUrl() -> String?
    func getPlace() -> String?
    func getTitle() -> String?
    func getSubTitle() -> String?
    func getBodyText() -> String?
    func getMedia() -> [String?]?
}

protocol DetailInteractorInterface: InteractorInterface {
}
