//
//  DetailPresenter.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    private let article: NewsModel?

    // MARK: - Lifecycle -

    init(view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface, model: NewsModel) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.article = model
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    func getContent() -> String? {
        article?.content?.text
    }
    
}
