//
//  DetailViewController.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import WebKit

final class DetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DetailPresenterInterface!
    
    private var scrollView: UIScrollView!
    private var mainImageView: UIImageView!
    private var placeTag: Tag!
    private var titleLabel: UILabel!
    private var subtitleLabel: UILabel!
    private var bodyLabel: UILabel!
    private var imagesStackView: UIStackView!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        initNavbar()
    }
    
    private func setup() {
        initScrollView()
        initMainImageView()
        initPlaceTag()
        initTitleLabel()
        initSubtitleLabel()
        initBodyLabel()
        initImagesStackView()
    }
    
    private func initScrollView() {
        scrollView = UIScrollView()
        scrollView.showsHorizontalScrollIndicator = false
        scrollView.showsVerticalScrollIndicator = true
        view.addSubview(scrollView)
        
        scrollView.snp.makeConstraints { make in
            make.top.equalTo(view.snp.top)
            make.leading.trailing.bottom.equalToSuperview()
        }
    }
    
    private func initMainImageView() {
        mainImageView = UIImageView()
        mainImageView.contentMode = .scaleAspectFit
    }
    
    private func initPlaceTag() {
        
    }
    
    private func initTitleLabel() {
        
    }
    
    private func initSubtitleLabel() {
        
    }
    
    private func initBodyLabel() {
        
    }
    
    private func initImagesStackView() {
        
    }
    
    private func initNavbar() {
        let sizeImage = UIImage(named: "ic_text_size")!
        let shareImage = UIImage(named: "ic_share")!
        let backImage = UIImage(named: "ic_chevron_left")!
        
        let sizeButton   = UIBarButtonItem(image: sizeImage,  style: .plain, target: self, action: #selector(didTapSizeButton(sender:)))
        let shareButton = UIBarButtonItem(image: shareImage,  style: .plain, target: self, action: #selector(didTapShareButton(sender:)))
        
        navigationItem.rightBarButtonItems = [sizeButton, shareButton]
        
        let backButton = UIBarButtonItem(image: backImage,  style: .plain, target: self, action: #selector(didTapBackButton(sender:)))
        navigationItem.leftBarButtonItems = [backButton]
        
        let titleImage = UIImage(named: "")
        navigationItem.titleView = UIImageView(image: titleImage)
    }
    @objc
    private func didTapSizeButton(sender: AnyObject){
        
    }
    
    @objc
    private func didTapShareButton(sender: AnyObject){
        
    }
    
    @objc
    private func didTapBackButton(sender: AnyObject){
        
    }

}

// MARK: - Extensions -

extension DetailViewController: DetailViewInterface {
}
extension DetailViewController: WKUIDelegate, WKNavigationDelegate {
    
}
