//
//  ExampleInterfaces.swift
//  BaseProject
//
//  Created by mac on 2021. 02. 08..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ExampleWireframeInterface: WireframeInterface {
}

protocol ExampleViewInterface: ViewInterface {
}

protocol ExamplePresenterInterface: PresenterInterface {
}

protocol ExampleInteractorInterface: InteractorInterface {
}
