//
//  ExampleWireframe.swift
//  BaseProject
//
//  Created by mac on 2021. 02. 08..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ExampleWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ExampleViewController()
        super.init(viewController: moduleViewController)

        let interactor = ExampleInteractor()
        let presenter = ExamplePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ExampleWireframe: ExampleWireframeInterface {
}
