//
//  ExamplePresenter.swift
//  BaseProject
//
//  Created by mac on 2021. 02. 08..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ExamplePresenter {

    // MARK: - Private properties -

    private unowned let view: ExampleViewInterface
    private let interactor: ExampleInteractorInterface
    private let wireframe: ExampleWireframeInterface

    // MARK: - Lifecycle -

    init(view: ExampleViewInterface, interactor: ExampleInteractorInterface, wireframe: ExampleWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ExamplePresenter: ExamplePresenterInterface {
}
