
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

inhibit_all_warnings!

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseProject
    pod 'MaterialComponents/ActivityIndicator'
    pod 'ObjectMapper', '~> 3.5.1'
 #   pod 'SDWebImage'
    pod 'SnapKit'
    pod 'SwiftyBeaver'
    pod 'Alamofire', '~> 5.0.0-rc.2'
    pod 'AlamofireObjectMapper', '~> 6.2.0'
    pod 'SwifterSwift'
    pod 'SwiftSoup'
    pod 'NVActivityIndicatorView'
 #   pod 'Firebase'
 #   pod 'Firebase/Analytics'
 #   pod 'Firebase/Auth'
 #   pod 'Firebase/Database'
end

target 'District8' do
  shared_pods
  target 'District8Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
  
target 'District8UITests' do
  # Pods for testing
end
