//
//  OverviewInterfaces.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol OverviewWireframeInterface: WireframeInterface {
}

protocol OverviewViewInterface: ViewInterface {
}

protocol OverviewPresenterInterface: PresenterInterface {
}

protocol OverviewInteractorInterface: InteractorInterface {
}
