//
//  OverviewPresenter.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OverviewPresenter {

    // MARK: - Private properties -

    private unowned let view: OverviewViewInterface
    private let interactor: OverviewInteractorInterface
    private let wireframe: OverviewWireframeInterface

    // MARK: - Lifecycle -

    init(view: OverviewViewInterface, interactor: OverviewInteractorInterface, wireframe: OverviewWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension OverviewPresenter: OverviewPresenterInterface {
}
