//
//  OverviewViewController.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OverviewViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: OverviewPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor(named: "Delft")
    }

}

// MARK: - Extensions -

extension OverviewViewController: OverviewViewInterface {
}
