//
//  OverviewWireframe.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OverviewWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = OverviewViewController()
        super.init(viewController: moduleViewController)

        let interactor = OverviewInteractor()
        let presenter = OverviewPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension OverviewWireframe: OverviewWireframeInterface {
    func openFilter() {
        let navController = BaseNavigationController()
        navController.setClearBackground()
        navController.modalTransitionStyle = .crossDissolve
        navController.modalPresentationStyle = .overCurrentContext
        navController.pushViewController(FilterPickerWireframe().viewController, animated: false)
        viewController.present(navController, animated: true, completion: nil)

    }
    
    func openDetails(model: NewsModel) {
        self.navigationController?.pushWireframe(DetailWireframe(model: model))
    }
    
    
}
