//
//  OverviewInteractor.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 29..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OverviewInteractor {
}

// MARK: - Extensions -

extension OverviewInteractor: OverviewInteractorInterface {
}
