//
//  TextSizePickerWireframe.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 31..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TextSizePickerWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = TextSizePickerViewController()
        super.init(viewController: moduleViewController)

        let interactor = TextSizePickerInteractor()
        let presenter = TextSizePickerPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TextSizePickerWireframe: TextSizePickerWireframeInterface {
}
