//
//  TextSizePickerInteractor.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 31..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class TextSizePickerInteractor {
}

// MARK: - Extensions -

extension TextSizePickerInteractor: TextSizePickerInteractorInterface {
}
