//
//  TextSizePickerViewController.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 31..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TextSizePickerViewController: BasePopUpViewController {

    // MARK: - Public properties -

    var presenter: TextSizePickerPresenterInterface!
    
    private var tableView: UITableView!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView = UITableView()
        tableView.layer.cornerRadius = 8.0.screenScaled
        tableView.layer.masksToBounds = true
        tableView.backgroundColor = .white
        tableView.register(TextSizeListItem.self, forCellReuseIdentifier: TextSizeListItem.cellId)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.separatorStyle = .none
        
        containerView.addSubview(tableView)
        tableView.snp.makeConstraints { make in
            make.leading.bottom.centerX.equalToSuperview()
            make.top.lessThanOrEqualTo(view.snp.centerY)
        }
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        removeStatusBarView()
    }

}

// MARK: - Extensions -

extension TextSizePickerViewController: TextSizePickerViewInterface {
}

extension TextSizePickerViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        4
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: TextSizeListItem.cellId, for: indexPath) as! TextSizeListItem
        let text = presenter.getOption(at: indexPath)
        cell.bind(text: text)
        if text == UserDefaults.standard.string(forKey: Constants.UserDefaults.TextSize) {
            cell.setSelected(true, animated: true)
        }
        if indexPath.row == (self.tableView(tableView, numberOfRowsInSection: 0))-1 {
            cell.hideSeparator()
        }
        cell.selectionStyle = .none
        return cell
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let headerView = UITableViewHeaderFooterView()
//        headerView.roundCorners([.topLeft, .topRight], radius: 8.0.screenScaled)
        let subview = PopupHeaderView()
        subview.bind(text: "TextSize".localized)
        headerView.addSubview(subview)
        subview.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
            
        let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap))
            tapRecognizer.delegate = self
            tapRecognizer.numberOfTapsRequired = 1
            tapRecognizer.numberOfTouchesRequired = 1
            headerView.addGestureRecognizer(tapRecognizer)
            return headerView
        
    }
    
    @objc
    private func handleTap() {
        transparentViewTapped()
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        UserDefaults.standard.setValue(presenter.getOption(at: indexPath), forKey: Constants.UserDefaults.TextSize)
        tableView.reloadData()
        NotificationCenter.default.post(name: Constants.Notifications.TextSizeChanged, object: nil)
    }
}
extension TextSizePickerViewController: UIGestureRecognizerDelegate {}
