//
//  TextSizePickerInterfaces.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 07. 31..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol TextSizePickerWireframeInterface: WireframeInterface {
}

protocol TextSizePickerViewInterface: ViewInterface {
}

protocol TextSizePickerPresenterInterface: PresenterInterface {
    func getOption(at indexPath: IndexPath) -> String
}

protocol TextSizePickerInteractorInterface: InteractorInterface {
}
