//
//  FilterPickerWireframe.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 08. 01..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FilterPickerWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = FilterPickerViewController()
        super.init(viewController: moduleViewController)

        let interactor = FilterPickerInteractor()
        let presenter = FilterPickerPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FilterPickerWireframe: FilterPickerWireframeInterface {
}
