//
//  FilterPickerInteractor.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 08. 01..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FilterPickerInteractor {
}

// MARK: - Extensions -

extension FilterPickerInteractor: FilterPickerInteractorInterface {
}
