//
//  FilterPickerPresenter.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 08. 01..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FilterPickerPresenter {

    // MARK: - Private properties -

    private unowned let view: FilterPickerViewInterface
    private let interactor: FilterPickerInteractorInterface
    private let wireframe: FilterPickerWireframeInterface

    private let options = ["Filter1".localized, "Filter2".localized, "Filter3".localized, "Filter4".localized ]

    // MARK: - Lifecycle -

    init(view: FilterPickerViewInterface, interactor: FilterPickerInteractorInterface, wireframe: FilterPickerWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FilterPickerPresenter: FilterPickerPresenterInterface {
    
    func getOption(at indexPath: IndexPath) -> String {
        options[indexPath.row]
    }
    
}
