//
//  FilterPickerInterfaces.swift
//  District8
//
//  Created by Hodi Zsuzsa on 2021. 08. 01..
//  Copyright (c) 2021. ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FilterPickerWireframeInterface: WireframeInterface {
}

protocol FilterPickerViewInterface: ViewInterface {
}

protocol FilterPickerPresenterInterface: PresenterInterface {
    func getOption(at indexPath: IndexPath) -> String
}

protocol FilterPickerInteractorInterface: InteractorInterface {
}
